import Head from 'next/head'
import Image from 'next/image'
import { useFormik } from 'formik'
import formImage from '../public/yellow.jpg'
import * as Yup from 'yup'
import { useRouter } from 'next/router'
import {motion as m} from 'framer-motion'

export default function Home() {

  //Router
  const  router = useRouter()



  // Formik Logics

  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "Spain",
      terms: ""
    },

    // validate Form

    validationSchema: Yup.object({
        name: Yup.string().max(20,"Name must be 20 characters or less.").required("Name is required"),
        email: Yup.string().email("Invalid email address.").required("Email is required"),
        terms: Yup.array().required("Terms of service must be checked")
    }),

    //Submit Form
    onSubmit: (values) => {
       console.log(values);
       router.push({pathname:"/success", query:values});
    },
  });

  console.log(formik.errors)

  // console.log(formik.values)

  return (
    <m.div 
    initial={{opacity:0}} 
    animate={{opacity:1}} 
    exit={{opacity:0}}
    className="w-full"
    >
      <Head>
        <title>Modern React Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center justify-center">

        <form 
          onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg w-1/2">
          <div className="flex-1 text-gray-700 p-20">

            <h1 className='text-3xl pb-2'>Let's get started ※</h1>
            <p className="text-lg text-gray-500 font-mono">
              if you are going through hell, keep going.
            </p>

            <div className="mt-6">

              {/* Name input field */}
              <div className="pb-4">
                <label 
                  className={`block text-sm pb-2 font-bold ${ formik.touched.name && formik.errors.name ? 'text-red-500':""}`} 
                  htmlFor="name"
                  >
                    {formik.touched.name && formik.errors.name ? formik.errors.name: "Name"}
                  </label>
                <input
                  className="border-4  outline-transparent focus:border-amber-200 p-2 rounded-md w-1/2 "
                  type="text"
                  name="name"
                  placeholder="Enter your name"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}

                />
              </div>


              {/* Email input field */}
              <div className="pb-4">
                <label 
                  className={ `block text-sm pb-2 font-bold ${ formik.touched.email && formik.errors.email ? 'text-red-500':""}`} 
                  htmlFor="email"
                  >
                  {formik.touched.email && formik.errors.email ? formik.errors.email: "Email"}
                  </label>
                <input
                  className="border-4 outline-transparent focus:border-amber-200 p-2 rounded-md w-1/2  focus:ring-amber-500 "
                  type="email"
                  name="email"
                  placeholder="Enter your email"
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* Country input field */}
              <div className="pb-4">
                <label className="block text-sm pb-2 font-bold" htmlFor="country">Country</label>
                <select value={formik.values.country}
                  onChange={formik.handleChange}
                  name="country"
                  className='border-4  outline-transparent focus:border-amber-200 p-2 rounded-md w-1/2  focus:ring-amber-500 '>

                  <option>United States</option>
                  <option>Spain</option>
                  <option>France</option>
                  <option>Venezuela</option>
                </select>
              </div>

              {/* Terms of service */}
              <div className="pb-4">
                <label 
                className={`block text-sm pb-2  font-bold ${ formik.touched.terms && formik.errors.terms ? 'text-red-500':""}`}
                htmlFor="terms"
                >
                  {formik.touched.terms && formik.errors.terms ? formik.errors.terms : "Terms of service"}
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    name="terms"
                    value="checked"
                    className="h-5 w-5 accent-pink-500 outline-pink-500"
                    onChange={formik.handleChange}
                  />
                  <p className="text-sm text-gray-500">
                    I agree to the Terms and Service that my data will be taken and sold.
                  </p>
                </div>
              </div>

              <button type="submit" className="bg-amber-400 hover:bg-amber-500 text-m text-white py-3 mt-6 rounded-lg w-full font-mono outline-pink-500 ">Start the journey!</button>

            </div>
          </div>

          <div className="relative flex-1">

            <Image alt="form-travel" src={formImage} fill className="object-cover rounded-lg" />


          </div>

        </form>

      </main>

    </m.div>
  )
}
